run:
  tests: false

  skip-dirs:
    - bin

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  staticcheck:
    go: "1.16.6"
    checks: [ "all" ]
  stylecheck:
    go: "1.16.6"
    checks: [ "all" ]
    go-import-whitelist:
     - fmt
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  prealloc:
    simple: false
    range-loops: true
    for-loops: true

linters:
  disable-all: true
  enable:
    - revive
    - staticcheck
    - stylecheck
    - gocyclo
    - gosimple
    - gocritic
    - staticcheck
    - gofmt
    - govet
    - prealloc